-- MySQL Script generated by MySQL Workbench
-- Sat Apr 21 19:36:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema NJITFitnessClub
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `NJITFitnessClub` ;

-- -----------------------------------------------------
-- Schema NJITFitnessClub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NJITFitnessClub` DEFAULT CHARACTER SET utf8 ;
USE `NJITFitnessClub` ;

-- -----------------------------------------------------
-- Table `NJITFitnessClub`.`Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NJITFitnessClub`.`Member` ;

CREATE TABLE IF NOT EXISTS `NJITFitnessClub`.`Member` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Address` VARCHAR(255) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `RegistrationDate` DATETIME NOT NULL,
  `Membership` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NJITFitnessClub`.`Membership`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NJITFitnessClub`.`Membership` ;

CREATE TABLE IF NOT EXISTS `NJITFitnessClub`.`Membership` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NOT NULL,
  `Fee` FLOAT NOT NULL,
  `Advantages` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NJITFitnessClub`.`ExerciseSchedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NJITFitnessClub`.`ExerciseSchedule` ;

CREATE TABLE IF NOT EXISTS `NJITFitnessClub`.`ExerciseSchedule` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Duration` FLOAT NOT NULL,
  `StartTime` DATETIME NOT NULL,
  `Room` INT NOT NULL,
  `ExerciseType` INT NOT NULL,
  `Instructor` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NJITFitnessClub`.`ExerciseType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NJITFitnessClub`.`ExerciseType` ;

CREATE TABLE IF NOT EXISTS `NJITFitnessClub`.`ExerciseType` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NJITFitnessClub`.`Room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NJITFitnessClub`.`Room` ;

CREATE TABLE IF NOT EXISTS `NJITFitnessClub`.`Room` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RoomNumber` VARCHAR(45) NOT NULL,
  `Capacity` INT NOT NULL,
  `BuildingName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NJITFitnessClub`.`Instructor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NJITFitnessClub`.`Instructor` ;

CREATE TABLE IF NOT EXISTS `NJITFitnessClub`.`Instructor` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Salary` FLOAT NULL,
  `Wage` FLOAT NULL,
  `NumberHoursTaught` FLOAT NULL,
  `MonthlyPayBeforeTaxes` FLOAT GENERATED ALWAYS AS (IF(ISNULL(`Wage`), (`Salary` / 12), ((`Wage` * `NumberHoursTaught`) / 12))) STORED,
  `MonthlyPayAfterTaxes` FLOAT GENERATED ALWAYS AS (`MonthlyPayBeforeTaxes` * 0.82) STORED,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NJITFitnessClub`.`MemberExerciseSchedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NJITFitnessClub`.`MemberExerciseSchedule` ;

CREATE TABLE IF NOT EXISTS `NJITFitnessClub`.`MemberExerciseSchedule` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Member` INT UNSIGNED NOT NULL,
  `ExerciseSchedule` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `NJITFitnessClub`.`Instructor`
-- -----------------------------------------------------
START TRANSACTION;
USE `NJITFitnessClub`;
INSERT INTO `NJITFitnessClub`.`Instructor` (`Name`, `Salary`, `Wage`, `NumberHoursTaught`) VALUES ('Maggie Jones',	36000, NULL, NULL);
INSERT INTO `NJITFitnessClub`.`Instructor` (`Name`, `Salary`, `Wage`, `NumberHoursTaught`) VALUES ('Samantha Higgins', NULL, 14,	275);
INSERT INTO `NJITFitnessClub`.`Instructor` (`Name`, `Salary`, `Wage`, `NumberHoursTaught`) VALUES ('Joe Seph',	50000, NULL, NULL);
INSERT INTO `NJITFitnessClub`.`Instructor` (`Name`, `Salary`, `Wage`, `NumberHoursTaught`) VALUES ('Michael Pascale',	NULL,	19,	400);
INSERT INTO `NJITFitnessClub`.`Instructor` (`Name`, `Salary`, `Wage`, `NumberHoursTaught`) VALUES ('Sarah Jacobs', NULL, 24,	475);
COMMIT;

-- -----------------------------------------------------
-- Data for table `NJITFitnessClub`.`Room`
-- -----------------------------------------------------
START TRANSACTION;
USE `NJITFitnessClub`;
INSERT INTO `NJITFitnessClub`.`Room` (`RoomNumber`, `Capacity`, `BuildingName`) VALUES (203, 12, 'CAMP');
INSERT INTO `NJITFitnessClub`.`Room` (`RoomNumber`, `Capacity`, `BuildingName`) VALUES (450,	15,	'COLT');
INSERT INTO `NJITFitnessClub`.`Room` (`RoomNumber`, `Capacity`, `BuildingName`) VALUES (132,	20,	'FAC');
INSERT INTO `NJITFitnessClub`.`Room` (`RoomNumber`, `Capacity`, `BuildingName`) VALUES (106,	20,	'CULM');
INSERT INTO `NJITFitnessClub`.`Room` (`RoomNumber`, `Capacity`, `BuildingName`) VALUES (105,	12,	'CULM');
INSERT INTO `NJITFitnessClub`.`Room` (`RoomNumber`, `Capacity`, `BuildingName`) VALUES (202,	10,	'CAMP');
INSERT INTO `NJITFitnessClub`.`Room` (`RoomNumber`, `Capacity`, `BuildingName`) VALUES (108,	10,	'YORK');
INSERT INTO `NJITFitnessClub`.`Room` (`RoomNumber`, `Capacity`, `BuildingName`) VALUES (110,	10,	'YORK');
INSERT INTO `NJITFitnessClub`.`Room` (`RoomNumber`, `Capacity`, `BuildingName`) VALUES (101,	5,	'CKB');
INSERT INTO `NJITFitnessClub`.`Room` (`RoomNumber`, `Capacity`, `BuildingName`) VALUES (303,	10,	'EBER');
INSERT INTO `NJITFitnessClub`.`Room` (`RoomNumber`, `Capacity`, `BuildingName`) VALUES (117,	50,	'STPG');
INSERT INTO `NJITFitnessClub`.`Room` (`RoomNumber`, `Capacity`, `BuildingName`) VALUES (403,	15,	'TIER');
INSERT INTO `NJITFitnessClub`.`Room` (`RoomNumber`, `Capacity`, `BuildingName`) VALUES (101,	8,	'OAK');
COMMIT;

-- -----------------------------------------------------
-- Data for table `NJITFitnessClub`.`ExerciseSchedule`
-- -----------------------------------------------------
START TRANSACTION;
USE `NJITFitnessClub`;
INSERT INTO `NJITFitnessClub`.`ExerciseSchedule` (`Duration`, `StartTime`, `Room`, `ExerciseType`, `Instructor`) VALUES (30,	'2018-04-22 12:30',	1,	1,	1);
INSERT INTO `NJITFitnessClub`.`ExerciseSchedule` (`Duration`, `StartTime`, `Room`, `ExerciseType`, `Instructor`) VALUES (45,	'2018-04-24 17:00',	2,	2,	2);
INSERT INTO `NJITFitnessClub`.`ExerciseSchedule` (`Duration`, `StartTime`, `Room`, `ExerciseType`, `Instructor`) VALUES (60,	'2018-4-25 19:30',	3,	5,	3);
INSERT INTO `NJITFitnessClub`.`ExerciseSchedule` (`Duration`, `StartTime`, `Room`, `ExerciseType`, `Instructor`) VALUES (60,	'2018-4-28 11:00',	4,	4,	3);
INSERT INTO `NJITFitnessClub`.`ExerciseSchedule` (`Duration`, `StartTime`, `Room`, `ExerciseType`, `Instructor`) VALUES (30,	'2018-4-22 16:00',	1,	3,	4);
INSERT INTO `NJITFitnessClub`.`ExerciseSchedule` (`Duration`, `StartTime`, `Room`, `ExerciseType`, `Instructor`) VALUES (30,	'2018-4-29 10:00',	5,	6,	4);
INSERT INTO `NJITFitnessClub`.`ExerciseSchedule` (`Duration`, `StartTime`, `Room`, `ExerciseType`, `Instructor`) VALUES (45,	'2018-5-1 17:00',	6,	7,	4);
INSERT INTO `NJITFitnessClub`.`ExerciseSchedule` (`Duration`, `StartTime`, `Room`, `ExerciseType`, `Instructor`) VALUES (60,	'2018-5-2 10:00',	2,	7,	5);
INSERT INTO `NJITFitnessClub`.`ExerciseSchedule` (`Duration`, `StartTime`, `Room`, `ExerciseType`, `Instructor`) VALUES (45,	'2018-5-2 13:00',	7,	8,	1);
INSERT INTO `NJITFitnessClub`.`ExerciseSchedule` (`Duration`, `StartTime`, `Room`, `ExerciseType`, `Instructor`) VALUES (30,	'2018-5-3 19:00',	8,	9,	1);
INSERT INTO `NJITFitnessClub`.`ExerciseSchedule` (`Duration`, `StartTime`, `Room`, `ExerciseType`, `Instructor`) VALUES (60,	'2018-5-6 11:00', 9, 10,	3);
INSERT INTO `NJITFitnessClub`.`ExerciseSchedule` (`Duration`, `StartTime`, `Room`, `ExerciseType`, `Instructor`) VALUES (30,	'2018-4-17 11:00', 10,	1,	2);
INSERT INTO `NJITFitnessClub`.`ExerciseSchedule` (`Duration`, `StartTime`, `Room`, `ExerciseType`, `Instructor`) VALUES (30,	'2018-4-18 17:00', 13,	2,	5);
INSERT INTO `NJITFitnessClub`.`ExerciseSchedule` (`Duration`, `StartTime`, `Room`, `ExerciseType`, `Instructor`) VALUES (60,	'2018-4-20 18:00', 12,	8,	5);
INSERT INTO `NJITFitnessClub`.`ExerciseSchedule` (`Duration`, `StartTime`, `Room`, `ExerciseType`, `Instructor`) VALUES (45,	'2018-4-21 18:00', 11,	4,	4);
COMMIT;


-- -----------------------------------------------------
-- Data for table `NJITFitnessClub`.`Member`
-- -----------------------------------------------------
START TRANSACTION;
USE `NJITFitnessClub`;
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Franny Hall', '435 Main Street, North Brunswick NJ 08902', '2017-2-1',	2);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Robert Hall', '435 Main Street, North Brunswick NJ 08902', '2017-2-1',	2);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Victoria Henderson', '8 Rosehill Court, New Brunswick NJ 08901',	'2017-2-15',	1);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Bryan Butler', '90 Alriel Street, Milltown NJ 08850', '2017-3-16',	3);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Belle Morris', '293 Enchanted Rose Drive, Newark NJ 07107', '2017-3-20',	2);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('May Price', '123 James Street, Newark NJ 07107', '2017-3-21',	1);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Christina Cox', '85349 Roku Road, New Brunswick NJ 08901', '2017-5-25',	3);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Martin Powell', '7483 Sunshine Lane, Elizabeth NJ 07201', '2017-6-20',	2);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Jessica Jenkins', '90-09 Fair Lawn Ave, Fair Lawn NJ 07410', '2017-7-7',	3);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Jasmine Long', '78 Cosmopolitan Country Road, Paramus NJ 07653', '2017-9-8',	3);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Christopher Reed', '289 Howard Ave, Rochelle Park NJ 07662', '2017-9-8',	2);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Chase Morgan', '788 Godwin Ave, Ridgewood NJ 07451', '2017-10-1',	2);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Greyson Grey', '185903 Toads Tavern Road, Glen Rock NJ 07452', '2017-10-2',	1);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Pete Peterson', '3 Tuffs Road, Ho-ho-kus NJ 07423', '2017-10-7',	1);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Tina Baker', '56 Hard Street, Haddonfield NJ 08033', '2017-10-19',	2);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Hilda Scott', '99 Mai Tai Court, Hackensack NJ 07602', '2017-11-1',	3);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('James Foster', '90 Coastal Cove Road, Bogota NJ 07608', '2017-11-2',	1);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Michelle Diaz', '10 Shipwreck Lane, Hasbrouck Heights NJ 07604', '2017-12-3',	2);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Jessica Green', '13 Pirate Pie Court, Bayonne NJ 07002', '2017-12-7',	1);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Molly Rodriguez', '4758 Mickey Mouse Street, Fairfield NJ 07004', '2017-12-8',	2);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Diamond White', '58 Bay Bagel Street, Boonton NJ 07005', '2017-12-10',	3);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Khloe Coleman', '4856 Princess Pike, Carteret NJ 07008', '2018-1-1',	3);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Pattie Perry', '1245 Mission Might Road, West Caldwell NJ 07007', '2018-1-1',	2);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Ross Flores', '303 Cliffs Road, Clifton NJ 07012', '2018-1-2',	1);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Cindy Simmons', '675843 Beach Way, Cliffside Park NJ 07010', '2018-1-17',	2);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Tiffany Murphy', '493 Ghost Lane, Fairfield NJ 07004', '2018-1-19',	3);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Kierra Cooper', '8 Way Off Way, Cedar Grove NJ 07009', '2018-1-29',	2);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Al Torres', '12 Salty Water Drive, Rahway NJ 07065', '2018-2-2',	1);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Juliana Richardson', '34 Window Wash Way, Colonia NJ 07067', '2018-2-6',	2);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Gabriel Cook', '1232 Winter Way, Roseland NJ 07068', '2018-2-8',	2);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Wendy Wellington', '22 Capitol St, Plainfield NJ 07060', '2018-2-9',	1);
INSERT INTO `NJITFitnessClub`.`Member` (`Name`, `Address`, `RegistrationDate`, `Membership`) VALUES ('Brittany Sike', '143 Fairfield Lane, Fairfield NJ 07004', '2018-2-15',	2);
COMMIT;


-- -----------------------------------------------------
-- Data for table `NJITFitnessClub`.`ExerciseType`
-- -----------------------------------------------------
START TRANSACTION;
USE `NJITFitnessClub`;
INSERT INTO `NJITFitnessClub`.`ExerciseType` (`Name`, `Description`) VALUES ('Zumba', 'Fuse Latin Rhythms and easy to follow moves to create a calorie burnin total body workout');
INSERT INTO `NJITFitnessClub`.`ExerciseType` (`Name`, `Description`) VALUES ('Spin', 'Bike through a high energy workout on our specialized cycles ');
INSERT INTO `NJITFitnessClub`.`ExerciseType` (`Name`, `Description`) VALUES ('Cardio Tai Box', 'A high energy, high impact blend of kicks and punches.');
INSERT INTO `NJITFitnessClub`.`ExerciseType` (`Name`, `Description`) VALUES ('Pilates', 'Develop a strong core in this ultimate body workout');
INSERT INTO `NJITFitnessClub`.`ExerciseType` (`Name`, `Description`) VALUES ('Boot Camp', 'Focus on your lower half in this intensive two part class. ');
INSERT INTO `NJITFitnessClub`.`ExerciseType` (`Name`, `Description`) VALUES ('Yoga', 'Physical, Mental, and Spiritual Practice of Stretching and Breathing');
INSERT INTO `NJITFitnessClub`.`ExerciseType` (`Name`, `Description`) VALUES ('POUND', 'A high-intensity interval workout that incorporates rhythmic moverments ');
INSERT INTO `NJITFitnessClub`.`ExerciseType` (`Name`, `Description`) VALUES ('Yoga Body Sculpt', 'A Strength-building class that focuses on sculting your thighs while flattening your belly');
INSERT INTO `NJITFitnessClub`.`ExerciseType` (`Name`, `Description`) VALUES ('Beach Body', 'Sculpting and Toning Body parts to get you ready for the sand and surf');
INSERT INTO `NJITFitnessClub`.`ExerciseType` (`Name`, `Description`) VALUES ('Overdrive', 'Shift your workout into overdrive with this interval training class');
COMMIT;


-- -----------------------------------------------------
-- Data for table `NJITFitnessClub`.`Membership`
-- -----------------------------------------------------
START TRANSACTION;
USE `NJITFitnessClub`;
INSERT INTO `NJITFitnessClub`.`Membership` (`Type`, `Fee`, `Advantages`) VALUES ('Premuim', 24.95, 'Workout Essentials, Locker Room with Showers, Group Fitness Classes, Live Workout Videos, Guest Passes, Free T-Shirt');
INSERT INTO `NJITFitnessClub`.`Membership` (`Type`, `Fee`, `Advantages`) VALUES ('Plus',	19.95, 'Workout Essentials, Locker Room with Showers, Group Fitness Classes, Live Workout Videos');
INSERT INTO `NJITFitnessClub`.`Membership` (`Type`, `Fee`, `Advantages`) VALUES ('Base',	9.95, 'Workout Essentials, Locker Room with Showers, Group Fitness Classes');
COMMIT;


-- -----------------------------------------------------
-- Data for table `NJITFitnessClub`.`MemberExerciseSchedule`
-- -----------------------------------------------------
START TRANSACTION;
USE `NJITFitnessClub`;
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (1,	1);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (2,	1);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (3,	1);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (4,	1);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (5,	1);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (3,	2);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (5,	2);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (6,	2);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (7,	2);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (9,	2);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (10,	2);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (11,	2);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (1,	3);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (2,	3);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (5,	3);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (7,	3);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (8,	3);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (4,	4);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (27,	4);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (32,	4);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (18,	4);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (20,	4);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (21,	4);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (22,	4);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (31,	4);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (9,	5);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (11,	5);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (27,	5);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (28,	6);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (29,	6);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (12,	6);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (13,	6);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (29,	6);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (5,	7);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (27,	7);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (28,	7);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (30,	7);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (32,	7);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (1,	7);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (3,	7);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (31,	7);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (13,	8);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (12,	8);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (11,	8);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (7,	8);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (14,	9);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (15,	9);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (26,	9);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (25,	9);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (15,	10);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (24,	10);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (30,	10);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (32,	10);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (6,	10);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (31,	10);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (31,	11);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (32,	11);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (30,	11);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (23,	11);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (22,	12);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (21,	12);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (16,	12);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (13,	12);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (14,	12);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (17,	12);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (18,	12);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (15,	13);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (19,	13);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (20,	13);
INSERT INTO `NJITFitnessClub`.`MemberExerciseSchedule` (`Member`, `ExerciseSchedule`) VALUES (16,	13);
COMMIT;